#!/usr/bin/env python3
"""Single source of truth for reading GAP-INR ablation held-out VALIDATION metrics.

Verified (unit-tested with decoys + cross-checked against raw files) to be byte-for-byte
consistent with the WRITING code (utils.log_metrics, build_atlas) and the trusted paper
reader summarize_eval.py:

  * DICE / SSIM  per epoch = mean over hold-out POSITIONS of (mean over eyes of the
    first-modality value). Read ONLY from the held-out leave-one-out dirs
    'val_eval_holdout_V{p}/' and 'val_eval_holdout_last/'. This reconstructs
    build_atlas's  _last_val_eval_dice  (build_atlas.py:947) EXACTLY, so the DICE
    curve's argmax IS the epoch checkpoint_best.pth was saved at (build_atlas.py:979).
    EXCLUDES the observed-visit TTO sets 'val_opt_*' (trivially easy) and the pooled
    aggregate 'val_eval_loo_avg' (would inflate the per-position mean).
  * lesion-MAE  per epoch = mean |Pred_Area_mm2 - GT_Area_mm2| over lesion-CSV rows
    whose Set starts with 'val_eval' (summarize_eval.py:216).

This module is imported by plot_epoch_curves.py, plot_grid_heatmap.py and
plot_grid_scatter.py so every figure reads the metrics identically.
"""
import csv as _csv
import glob
import json
import os
import re
import numpy as np


# ============================== the full latent grid ==============================
# 6 channel values x 6 spatial values (incl. S=1 global-vector) = 36 combinations. The two round-2
# sweeps (channel column @ spatial 32, spatial row @ 64 channels) already cover 10 cells; the other
# 26 are generated by  make_configs.py --gridsweep  as r2_a9_grid_c{C}_s{S} (S=1 = the 1D-latent row).
GRID_CHANNELS = [16, 32, 64, 128, 256, 512]
GRID_SPATIAL = [1, 8, 16, 32, 64, 128]   # S=1 = the global-vector (1D latent) ablation column

# (C, S) -> already-trained round-2 run name (the rest fall back to the grid name below).
_EXISTING = {
    (16, 32): "r2_a9_chan16", (32, 32): "r2_a9_chan32", (64, 32): "r2_a9_base",
    (128, 32): "r2_a9_chan128", (256, 32): "r2_a9_chan256", (512, 32): "r2_a9_chan512",
    (64, 8): "r2_a9_latent8", (64, 16): "r2_a9_latent16",
    (64, 64): "r2_a9_latent64", (64, 128): "r2_a9_latent128",
}


def grid_run_name(channels, spatial):
    """Run-dir name for a (channels, spatial) cell. MUST match make_configs.py naming."""
    return _EXISTING.get((channels, spatial), f"r2_a9_grid_c{channels}_s{spatial}")


def discover_grid(runs_root):
    """Map (channels, spatial) -> run-dir NAME by reading each run's ACTUAL latent_dim from its
    config_atlas.yaml (searched recursively). Server-agnostic: correct regardless of how the dirs are
    named (e.g. the 256x32 baseline may be 'r2_a9_base' on one server, 'r2_a9_chan256' on another).
    Returns {} if configs can't be read, so callers fall back to the name convention (grid_run_name)."""
    import glob as _glob
    try:
        import yaml
    except Exception:
        return {}
    out = {}
    if not os.path.isdir(runs_root):
        return {}
    for name in sorted(os.listdir(runs_root)):
        d = os.path.join(runs_root, name)
        if not os.path.isdir(d):
            continue
        cfgs = ([os.path.join(d, "config_atlas.yaml")] if os.path.exists(os.path.join(d, "config_atlas.yaml"))
                else sorted(_glob.glob(os.path.join(d, "**", "config_atlas.yaml"), recursive=True)))
        for cfg in cfgs:
            try:
                ld = yaml.safe_load(open(cfg))["inr_decoder"]["latent_dim"]
            except Exception:
                continue
            if isinstance(ld, (list, tuple)) and len(ld) == 3:
                out.setdefault((int(ld[0]), int(ld[1])), name)   # first config found wins
                break
    return out


# ------------------------------------------------------------------ data loading
def _load_metric_json(path):
    """metric -> list of per-eye scalars (first modality, NaN-padded), from a GAP-INR metrics JSON."""
    d = json.load(open(path))
    out = {}
    for entry in d:
        for k, v in entry.items():
            if k == "Subject":
                continue
            val = (v[0] if isinstance(v, list) and len(v) else
                   (np.nan if isinstance(v, list) else v))
            try:
                out.setdefault(k, []).append(float(val) if val is not None else np.nan)
            except (TypeError, ValueError):
                out.setdefault(k, []).append(np.nan)
    return out


def _is_val_eval_holdout_dir(dirname):
    """True only for the held-out leave-one-out VAL rounds whose per-position means feed
    build_atlas's _last_val_eval_dice: 'val_eval_holdout_V{p}' / 'val_eval_holdout_last'.
    Excludes observed-visit TTO sets ('val_opt_*') and the pooled aggregate ('val_eval_loo_avg')."""
    return dirname.startswith("val_eval") and "holdout" in dirname


def epoch_series(run_dir):
    """{epoch: {'DICE':mu, 'SSIM':mu, 'areaMAE':mu}} reproducing build_atlas's checkpoint metric.

    DICE/SSIM: per held-out position dir, mean over eyes of the first-modality value
    (matching log_metrics/_mean_dice); then mean ACROSS positions -> == _last_val_eval_dice.
    areaMAE : pooled mean |Pred-GT| over lesion-CSV rows whose Set starts with 'val_eval'.
    Returns {} if the run dir holds no held-out val data.
    """
    # epoch -> {position_dir -> {'DICE':posmean, 'SSIM':posmean}}
    pos_means = {}
    for jp in glob.glob(os.path.join(run_dir, "**", "*_metrics_ep=*.json"), recursive=True):
        dname = os.path.basename(os.path.dirname(jp))
        if not _is_val_eval_holdout_dir(dname):
            continue
        m = re.search(r"ep=(\d+)", os.path.basename(jp))
        if not m:
            continue
        ep = int(m.group(1))
        mt = _load_metric_json(jp)
        rec = pos_means.setdefault(ep, {}).setdefault(dname, {})
        for key in ("DICE", "SSIM", "LPIPS", "PSNR"):
            vals = [v for v in mt.get(key, []) if v is not None and not np.isnan(v)]
            if vals:
                rec[key] = float(np.mean(vals))

    series = {}
    for ep, bydir in pos_means.items():
        rec = {}
        for key in ("DICE", "SSIM", "LPIPS", "PSNR"):
            posv = [d[key] for d in bydir.values() if key in d]
            if posv:
                rec[key] = float(np.mean(posv))
        series[ep] = rec

    per_ep_area = {}
    for cp in glob.glob(os.path.join(run_dir, "**", "lesion_areas*_epoch_*.csv"), recursive=True):
        m = re.search(r"epoch_(\d+)", os.path.basename(cp))
        if not m:
            continue
        ep = int(m.group(1))
        with open(cp) as f:
            for row in _csv.DictReader(f):
                if not str(row.get("Set", "")).startswith("val_eval"):
                    continue
                try:
                    diff = abs(float(row["Pred_Area_mm2"]) - float(row["GT_Area_mm2"]))
                except (KeyError, ValueError, TypeError):
                    continue
                per_ep_area.setdefault(ep, []).append(diff)
    for ep, diffs in per_ep_area.items():
        if diffs:
            series.setdefault(ep, {})["areaMAE"] = float(np.mean(diffs))
    return series


def best_epoch_by_dice(series):
    """Epoch of highest mean held-out DICE == the epoch checkpoint_best.pth was saved at."""
    cand = [(ep, r["DICE"]) for ep, r in series.items() if "DICE" in r and not np.isnan(r["DICE"])]
    return max(cand, key=lambda t: t[1])[0] if cand else None


def reeval_lpips(run_dir):
    """LPIPS_mean from a config's reeval_loo summary (leave_one_out_summary_reeval_*.csv), used as a
    fallback when the per-epoch training-curve LPIPS is missing (the cold-cache race disabled it).
    Prefers the 'last'/extrapolation summary; returns a float or None."""
    for name in ("leave_one_out_summary_reeval_last.csv",
                 "leave_one_out_summary_reeval_leave_one_out.csv"):
        for p in sorted(glob.glob(os.path.join(run_dir, "**", name), recursive=True)):
            try:
                rows = list(_csv.DictReader(open(p)))
            except Exception:
                continue
            row = next((r for r in rows if "extrapolation" in (r.get("group", "") or "").lower()),
                       rows[0] if rows else None)
            if not row:
                continue
            try:
                v = float(row.get("LPIPS_mean", ""))
                if v == v:                                  # not NaN
                    return v
            except (TypeError, ValueError):
                pass
    return None


def inject_reeval_lpips(series, runs_root, seg_weights=(1.0, 1.0)):
    """For every grid cell whose Stage-A best checkpoint has NO LPIPS in its training curve, pull
    LPIPS from that config's reeval_loo summary and write it into `series` at that epoch, so it is
    seen by BOTH the Stage-B ranking and the LPIPS panel. Mutates `series`; returns the list of
    (cell, epoch, lpips) patched."""
    stageA, _ = grid_best_checkpoints(series, weights=seg_weights, metric_keys=SELECT_KEYS_SEG)
    patched = []
    for cell, a in stageA.items():
        ep = a["best_epoch"]
        rec = series.get(cell, {}).get(ep)
        if rec is None:
            continue
        v = rec.get("LPIPS")
        if v is not None and not (isinstance(v, float) and np.isnan(v)):
            continue                                        # training-curve LPIPS already present
        lp = reeval_lpips(os.path.join(runs_root, grid_run_name(*cell)))
        if lp is not None:
            rec["LPIPS"] = lp                               # rec is the live series dict -> in place
            patched.append((cell, ep, lp))
    return patched


# ---------------------------------------------- composite (trade-off) selection
METRIC_KEYS = ("DICE", "SSIM", "areaMAE")
LOWER_BETTER = ("areaMAE", "LPIPS")

# 4-metric checkpoint selection: segmentation (DICE) + lesion size (areaMAE) + reconstruction
# quality (SSIM up, LPIPS down). Used by plot_grid_metric_scatter.py so the SAME checkpoint is
# picked for every displayed metric. LPIPS/areaMAE are lower-better (see LOWER_BETTER).
SELECT_KEYS = ("DICE", "SSIM", "LPIPS", "areaMAE")

# 2-metric checkpoint selection: the epoch with the best segmentation (DICE up) AND lesion-size
# (areaMAE down) trade-off. Reconstruction metrics (PSNR/SSIM/LPIPS) are then merely REPORTED at
# that epoch, not used to pick it. Used by plot_grid_metric_row.py.
SELECT_KEYS_SEG = ("DICE", "areaMAE")

# Stage-B config-ranking metrics: the FULL composite (segmentation + reconstruction) applied across
# configs at their Stage-A best checkpoints. Same equal-weight min-max composite criterion as before,
# now also crediting reconstruction quality (PSNR/SSIM up, LPIPS down).
RANK_KEYS = ("DICE", "SSIM", "LPIPS", "PSNR", "areaMAE")


def grid_best_checkpoints(series_by_cfg, weights=(1.0, 1.0, 1.0),
                          metric_keys=METRIC_KEYS, lower_better=LOWER_BETTER):
    """Choose each config's best checkpoint by the DICE/SSIM/lesion-MAE TRADE-OFF.

    Every metric is min-max normalized to [0,1] ACROSS ALL (config, epoch) points that
    have all three metrics present (so the normalization is shared -> composites are
    comparable across the whole grid). Lower-is-better metrics (lesion-area MAE) are
    inverted so 1 = best. composite = weighted mean of the normalized metrics; each
    config's best epoch = the epoch maximizing that composite.

    Args:
        series_by_cfg: {cfg_key: epoch_series(run_dir)}  (cfg_key is any hashable, e.g. (C,S))
        weights      : relative weights for (DICE, SSIM, areaMAE); default equal.
    Returns:
        best: {cfg_key: {'best_epoch', 'composite', raw + '_n' normalized per metric}}  (only
              configs with >=1 fully-populated epoch), and
        norm: {metric: (lo, hi)} the shared min-max ranges (for annotating/colorbars).
    """
    w = {k: float(wt) for k, wt in zip(metric_keys, weights)}
    wsum = sum(w.values()) or 1.0

    # 1) shared min-max ranges over every fully-populated (cfg, epoch)
    pool = {k: [] for k in metric_keys}
    for series in series_by_cfg.values():
        for rec in series.values():
            if all(k in rec and not np.isnan(rec[k]) for k in metric_keys):
                for k in metric_keys:
                    pool[k].append(rec[k])
    norm = {}
    for k in metric_keys:
        if pool[k]:
            lo, hi = float(np.min(pool[k])), float(np.max(pool[k]))
        else:
            lo, hi = 0.0, 1.0
        norm[k] = (lo, hi)

    def _normalized(k, v):
        lo, hi = norm[k]
        if hi <= lo:
            return 1.0
        n = (v - lo) / (hi - lo)
        return (1.0 - n) if k in lower_better else n

    # 2) per config: composite per epoch, then argmax
    best = {}
    for cfg, series in series_by_cfg.items():
        cand = []
        for ep, rec in series.items():
            if not all(k in rec and not np.isnan(rec[k]) for k in metric_keys):
                continue
            comp = sum(w[k] * _normalized(k, rec[k]) for k in metric_keys) / wsum
            cand.append((ep, comp, rec))
        if not cand:
            continue
        ep, comp, rec = max(cand, key=lambda t: t[1])
        entry = {"best_epoch": ep, "composite": comp}
        for k in metric_keys:
            entry[k] = rec[k]
            entry[k + "_n"] = _normalized(k, rec[k])
        best[cfg] = entry
    return best, norm


def two_stage_select(series_by_cfg, seg_weights=(1.0, 1.0), rank_weights=None,
                     seg_keys=SELECT_KEYS_SEG, rank_keys=RANK_KEYS, lower_better=LOWER_BETTER,
                     rank_on_common=False):
    """Two-stage config selection (checkpoint by segmentation, ranking by the full composite).

    Stage A -- best checkpoint PER config: pick best_epoch by the DICE + lesion-MAE composite
        (seg_keys). This is the segmentation-focused early-stopping decision.
    Stage B -- rank ACROSS configs: apply the SAME composite criterion (grid_best_checkpoints:
        per-metric min-max normalize across the compared points, invert lower-better, equal-weight
        mean) over rank_keys -- which ALSO credits reconstruction (PSNR/SSIM up, LPIPS down) --
        evaluated ONLY at each config's Stage-A best checkpoint. So a config's ranking score sees
        reconstruction quality, but the checkpoint that fixes every reported number is chosen on
        segmentation alone.

    If rank_on_common=True, any rank_key that is missing/NaN for even ONE Stage-A checkpoint is
    dropped from the ranking metric set, so EVERY config is ranked on the same (common) subset --
    nothing is silently excluded. Otherwise configs missing a rank_key are absent from stageB.

    Returns (stageA, stageB, normB, rank_keys_used):
        stageA[cfg] = {'best_epoch', 'composite'(seg), seg_keys raw + '_n'}
        stageB[cfg] = {'best_epoch' (== Stage A), 'composite'(rank), rank_keys_used raw + '_n'}
        normB       = {metric: (lo, hi)} Stage-B min-max ranges over the best-checkpoint points.
        rank_keys_used = the metric tuple actually used for the ranking.
    """
    stageA, _ = grid_best_checkpoints(series_by_cfg, weights=seg_weights,
                                      metric_keys=seg_keys, lower_better=lower_better)
    # freeze each config to a single-epoch "series" holding only its Stage-A best checkpoint, so the
    # Stage-B composite normalizes across configs' best checkpoints (not across all epochs).
    frozen = {cfg: {a["best_epoch"]: series_by_cfg[cfg][a["best_epoch"]]}
              for cfg, a in stageA.items()}

    keys = list(rank_keys)
    weights = list(rank_weights) if rank_weights is not None else None
    if rank_on_common and frozen:
        def _present(k):
            for fs in frozen.values():
                rec = next(iter(fs.values()))
                v = rec.get(k)
                if v is None or (isinstance(v, float) and np.isnan(v)):
                    return False
            return True
        keep = [i for i, k in enumerate(rank_keys) if _present(k)]
        keys = [rank_keys[i] for i in keep]
        if weights is not None:
            weights = [weights[i] for i in keep]
    if weights is None:
        weights = [1.0 for _ in keys]
    stageB, normB = grid_best_checkpoints(frozen, weights=tuple(weights),
                                          metric_keys=tuple(keys), lower_better=lower_better)
    return stageA, stageB, normB, tuple(keys)
